name: Deploy HTML to GitHub Pages

# Trigger the workflow when pushing to the main branch
on:
  push:
    branches:
      - main

# Define jobs
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/action-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/jom/Documents/DevOps/DevOps-Repo
